const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = './routes/routes.js'


const doc = {
    info: {
        version: "1.0.0",
        title: "PRODUCT REST API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Product",
            "description": "Endpoints"
        }
    ],
    definitions: {
        Product: {
            productName: "ServiceNow",
            productOwnerName: "Sarh Son",
            developers: [
                "TK Jin",
                "Naomi Jung",
                "Harry Potter"
            ],
            scrumMasterName: "Mack Kim",
            startDate: "2023/04/01",
            methodology:"Agile"
        },
        CreateProduct: {
            productName: "ServiceNow",
            productOwnerName: "Sarh Son",
            developers: [
                "TK Jin",
                "Naomi Jung",
                "Harry Potter"
            ],
            scrumMasterName: "Mack Kim",
            startDate: "2023/04/01",
            methodology:"Agile"
        }
    }
}


swaggerAutogen(outputFile, endpointsFiles,doc).then(() => {
    require('./server.js')
})